version: '3.8'
services: 
  nats: 
    image : nats:latest
    container_name: nats-server
    hostname: nats-server
    ports:
      - "4222:4222"
    networks:
      - back-nats
      - nats-mid

  java-backend:
    build: ./interstore
    container_name: java-backend 
    depends_on:
      - nats
    environment:
      - NATS_URL=nats://nats-server:4222
    command: [./gradlew , "run"]
    ports:
      - "8080:8080"
    networks:
      - back-nats
  
  react-browser:
    build: ./react-browser
    hostname: react-browser
    container_name: react-browser
    environment:
      - EXPRESS_URL=http://express-mid:5000
    ports:
      - 3001:3001
    command: ["npm","start"]
    networks:
      - mid-front

  express-mid:
    build: ./express-mid
    hostname: express-mid
    container_name: express-mid
    environment:
      - NATS_URL=nats://nats-server:4222
    ports:
      - 5000:5000
    networks:
      - nats-mid
      - mid-front
    command: ["node", "index.js"]
    

networks:
  back-nats:
  nats-mid:
  mid-front:

 
