version: '3.8'
services: 
  nats: 
    image: nats:latest
    container_name: nats-server
    hostname: nats-server
    ports:
      - "0.0.0.0:4222:4222"  # Expose to all interfaces
      - "0.0.0.0:8222:8222"  # Management interface
    command: ["-m", "8222", "--jetstream", "--addr", "0.0.0.0"]
    networks:
      - back-nats
    restart: unless-stopped 

  java-backend:
    build: 
      context: ./interstore
      dockerfile: Dockerfile
    image: nithinmanuel9/interstoretestieee2030-server:1.1  
    container_name: java-backend 
    depends_on:
      - nats
    environment:
      - NATS_URL=nats://nats-server:4222
      - SERVER_PORT=8080
      - SERVER_ADDRESS=0.0.0.0
    volumes:
      - ./interstore/app/certs:/app/certs:ro
    ports:
      - "8080:8080"
      
    networks:
      - back-nats
    restart: unless-stopped   
  

  react-browser:
    build:
      context: ./react-browser
      dockerfile: Dockerfile
    image: nithinmanuel9/interstoretestreact-browser:1.0  
    hostname: react-browser
    container_name: react-browser
    environment:
      - REACT_APP_API_URL=http://localhost:8080
    ports:
      - 3000:3000
    command: ["npm","start"]
    networks:
      - back-nats
    restart: unless-stopped   
            


networks:
  back-nats:
