version: '3.8'
services: 
  nats: 
    image: nats:latest
    container_name: nats-server
    hostname: nats-server
    ports:
      - "4222:4222"
      - "8222:8222" 
    command: ["-m", "8222", "--jetstream"]
    networks:
      - back-nats
      - nats-mid
    restart: unless-stopped 

  java-backend:
    build: 
      context: ./interstore
      dockerfile: Dockerfile
    image: nithinmanuel9/interstoretestieee2030-server:1.1  
    container_name: java-backend 
    depends_on:
      - nats
    environment:
      - NATS_URL=nats://nats-server:4222
      - SERVER_PORT=1900
      - SERVER_ADDRESS=0.0.0.0
    volumes:
      - ./interstore/app/certs:/app/certs:ro
    ports:
      - "8443:8443"
      - "1900:1900"
      
    networks:
      - back-nats
      - nats-mid
    restart: unless-stopped   
  

  react-browser:
    build:
      context: ./react-browser
      dockerfile: Dockerfile
    image: nithinmanuel9/interstoretestreact-browser:1.0  
    hostname: react-browser
    container_name: react-browser
    environment:
      - EXPRESS_URL=http://express-mid:5000
    ports:
      - 3001:3001
    command: ["npm","start"]
    networks:
      - mid-front
      - nats-mid
    restart: unless-stopped   
            
  express-mid:
    build: ./express-mid
    image: nithinmanuel9/interstoretestexpress-mid:1.0
    hostname: express-mid
    container_name: express-mid
    environment:
      - NATS_URL=nats://nats-server:4222
    volumes:
      - type: bind
        source: ./express-mid
        target: /express
    ports:
      - 5000:5000
    networks:
      - nats-mid
      - mid-front
      - back-nats
    restart: unless-stopped   
    command: ["node","index.js"]


# Commented out secrets - now using volumes for .pem files
# secrets:
#   server-keystore:
#     file: ./interstore/app/server-keystore.p12
#   truststore:
#     file: ./interstore/app/truststore.p12

networks:
  back-nats:
  nats-mid:
  mid-front:
