version: '3.8'
services: 
  nats: 
    image : nats:latest
    container_name: nats-server
    hostname: nats-server
    ports:
      - "4222:4222"
    networks:
      - back-nats
      - nats-front

  java-backend:
    build: ./interstore
    container_name: java-backend 
    depends_on:
      - nats
    environment:
      - NATS_URL=nats://nats-server:4222
    command: ["./gradlew", "run"]
    ports:
      - "8080:8080"
    networks:
      - back-nats

  electron-frontend:
    build: ./electron-react-app
    hostname: electron-frontend
    container_name: electron-frontend
    environment:
      - NATS_URL=nats://nats-server:4222
    ports:
      - 5900:5900
    command: ["tail","-f"]
    networks:
      - nats-front

networks:
  back-nats:
  nats-front:
