version: '3.8'
services:
  nats:
    image: nats:latest
    container_name: nats-server
    hostname: nats-server
    ports:
      - "4222:4222"
    networks:
      - back-nats
      - nats-mid
  java-backend:
    build:
      context: ./interstore
      dockerfile: Dockerfile
    container_name: java-backend
    depends_on:
      - nats
    volumes:
      - type: bind
        source: ./interstore
        target: /app   
    environment:
      - NATS_URL=nats://nats-server:4222
    command: ["./gradlew", "run"]  
   
    ports:
      - "8080:8080"
    networks:
      - back-nats
    working_dir: /app
  

  electron-frontend:
    build: ./electron-react-app
    hostname: electron-frontend
    container_name: electron-frontend
    environment:
      - EXPRESS_URL=http://express-mid:6000
    ports:
      - 9000:9000
    command: ["tail","-f"]
    networks:
      - mid-front
    volumes:
      - type: bind
        source: ./react-browser
        target: /react
    working_dir: /app

  express-mid:
    build: ./express-mid
    hostname: express-mid
    container_name: express-mid
    environment:
      - NATS_URL=nats://nats-server:4222
    ports:
      - 6000:6000
    networks:
      - nats-mid
      - mid-front
    command: ["node", "index.js"]
    volumes:
      - type: bind
        source: ./express-mid
        target: /express 
   

networks:
  back-nats:
  nats-mid:
  mid-front:

 #command: ["./gradlew", "run"]
   #volumes:
     # - ./interstore:/app
     # -  /app/build
  #command: ["./gradlew", "run", "--continuous"]  
     #volumes:
      #- ./electron-react-app:/app
 #volumes:
     # - ./express-mid:/app